services:
  m2txt:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: m2txt
    volumes:
      - ..:/app:delegated
    working_dir: /app
    tty: true
    stdin_open: true
